dataset = read.csv('iqsize.csv')
library(GGally)
ggpairs(dataset)
regressor = lm(PIQ ~ ., data = dataset)
summary(regressor)
y_pred = predict(regressor, newdata = dataset)
plot(y_pred, resid(regressor))
plot(y_pred, stdres(regresssor))
plot(dataset$Brain, stdres(regressor))
plot(dataset$Height, stdres(regressor))
plot(regressor)
regressor = lm(PIQ ~ Brain + Height, data =  dataset)
plot(dataset$Weight, stdres(regressor))
regressor = lm(PIQ ~ Weight + Height, data =  dataset)
plot(dataset$Brain, stdres(regressor))

regressor = lm(PIQ ~ Brain + Height, data =  dataset)

install.packages('nortest')
library('nortest')
ad.test(stdres(regressor))
shapiro.test(stdres(regressor))
lillie.test(stdres(regressor))
