select * from REGIONS;
select * from countries;
select * from locations;
select * from departments;
select * from jobs;
select * from employees;
select * from JOB_HISTORY;

select R.REGION_ID, R.REGION_NAME,
        C.COUNTRY_ID,C.COUNTRY_NAME, 
        L.LOCATION_ID, L.STREET_ADDRESS, L.CITY,
        D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.MANAGER_ID,
        J.JOB_ID,J.JOB_TITLE,J.MAX_SALARY,J.MAX_SALARY,
        E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.EMAIL,E.HIRE_DATE,E.SALARY,E.DEPARTMENT_ID,E.COMMISSION_PCT,
        JH.START_DATE,JH.END_DATE
from 
regions R LEFT OUTER JOIN COUNTRIES C
ON R.REGION_ID =C.REGION_ID
LEFT OUTER JOIN LOCATIONS L
ON C.COUNTRY_ID=L.COUNTRY_ID
LEFT OUTER JOIN DEPARTMENTS D
ON D.LOCATION_ID=L.LOCATION_ID
LEFT OUTER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
RIGHT OUTER JOIN JOBS J
ON J.JOB_ID=E.JOB_ID
LEFT JOIN JOB_HISTORY JH
ON JH.JOB_ID=J.JOB_ID AND 
JH.DEPARTMENT_ID=D.DEPARTMENT_ID;